MultiplyTrainerOnline/urls.py
from django.contrib import admin
from django.urls import path, include
from Trainer.views import Start_App


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Start_App.as_view(), name='start'),
    path('mathtrainer/', include('Trainer.urls', namespace='mathtrainer'))

]

Trainer/urls.py
from django.urls import path
from Trainer.views import Start, TrainerApp, Finish, Enter_Result

app_name='mathtrainer'

urlpatterns = [
    path('', Start.as_view(), name='math_start'),
    path('trainer/', TrainerApp.as_view(), name='trainer_app'),
    path('finish/', Finish.as_view(), name='finish'),
    path('sent_result/', Enter_Result.as_view(), name='enter_result'),
    ]

Trainer/models.py
from django.db import models

class Result(models.Model):
    name=models.CharField(max_length=20)
    total_tasks=models.IntegerField()
    mistakes=models.IntegerField()
    number_of_sessions=models.IntegerField(default=0)
    examples_of_mistakes=models.TextField()
    time=models.DateTimeField(auto_now=True)


class Game(models.Model):
    permission=models.BooleanField(default=True) # forbid start again if task dont complete
    number_of_tasks=models.IntegerField()
    total=models.IntegerField()
    number_example=models.IntegerField(default=1)
    mistakes=models.IntegerField()
    mistakes_examples=models.JSONField(default=[])
    tasks=models.JSONField(default=[])
    total_for_save=models.IntegerField()
    mistakes_for_save=models.IntegerField()
    session=models.IntegerField()
    action=models.CharField(max_length=10)

Trainer/forms.py
from django.forms import ModelForm

from Trainer.models import Result

class MyResultForm(ModelForm):
    class Meta:
        model=Result
        exclude=('total_tasks', 'mistakes', 'examples_of_mistakes', 'time', 'number_of_sessions')
        labels={'name':'Введи сюда свое имя, УЧЕНИК',
                }

Trainer/views.py
import random
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.views import View
from Trainer import modulle
from Trainer.models import Game
from Trainer.forms import MyResultForm

class Start_App(View):
    def get(self, request):
        print('index')
        return render(request, 'index.html')


class Start(View):
    def get(self, request):

        try:
            print('doing query')
            game=Game.objects.order_by('id')[0]
            print(Game.objects.order_by('id')[0])
            if game.permission==False:
                return redirect('mathtrainer:trainer_app')
        except IndexError:
            print('have index error')
            return render(request, 'mathtrainer.html')


    def post(self, request):
            try:
                if int(request.POST.get('number')) > 0 and request.POST.get('difficult') != None:
                        number_of_tasks=int(request.POST.get('number'))
                        action=request.POST.get('difficult')
                        game=Game(permission=False, number_of_tasks=number_of_tasks, total=number_of_tasks,
                                  action=action, tasks=modulle.choice_number(number_of_tasks,action), session=1,
                                  mistakes=0,  total_for_save=0, mistakes_for_save=0)
                        game.save()

                        return redirect('mathtrainer:trainer_app')

            except ValueError:
                return render(request, 'index.html')

            return render(request, 'mathtrainer.html')


class TrainerApp(View):
    def get(self, request):
        #if number_example>=total:
        #return redirect('finish')
        try:
            data=Game.objects.order_by('id')[0]
            all_tasks = data.tasks
            a, b, result = all_tasks[:].pop().values()
        except IndexError:
            return redirect('mathtrainer:finish')
            data.save()

        data.save()
        return render(request,'trainer_app.html', {'a': a, 'b': b,
                                                   'result': result, 'number_task': data.number_example})

    def post(self, request):
        try:
            data = Game.objects.order_by('id')[0]
            try:
                a, b, result = data.tasks.pop().values()
            except IndexError:
                return redirect('mathtrainer:finish')

            if int(request.POST.get('answer')) == int(result):
                messages.success(request, 'ПРАВИЛЬНО')

            elif int(request.POST.get('answer')) != int(result):
                messages.error(request, 'НЕ ПРАВИЛЬНО')
                data.mistakes+= 1
                data.tasks.insert(0,{'a': a, 'b': b, 'result': result})


        except ValueError:
            return render(request, 'trainer_app.html', { 'a': a, 'b': b,
                                                         'result': result, 'number_task': data.number_example })


        data.number_example += 1
        if data.number_example == data.total+1:
            data.save()
            return redirect('mathtrainer:finish')
        data.save()


        return redirect(request.path)

class Finish(View):
    def get(self, request):
        data=Game.objects.order_by('id')[0]
        images=['https://upload.wikimedia.org/wikipedia/commons/4/4f/Tesla_Model_S_02_2013.jpg',
               'https://autoreview.ru/images/Article/1609/Article_160932_860_575.jpg',
               'https://auto.ironhorse.ru/wp-content/uploads/1977/11/412.jpg']
        result, mistakes = data.total, data.mistakes
        if mistakes/result<=0.2:
            image=images[0]
        elif 0.2<mistakes/result<0.4:
            image=images[1]
        else:
            image=images[2]
        if mistakes==0:
            return render(request, 'finish.html', {'result': result, 'mistakes': mistakes, 'image':image, 'button':True})


        if mistakes>0 and data.session==1:
            data.mistakes_examples=data.tasks[:]
            data.total_for_save=result
            data.tasks*=5
            data.session+=1

        random.shuffle(data.tasks)
        data.total, data.mistakes, data.number_example = len(data.tasks), 0, 1
        data.save()
        return render(request, 'finish.html', {'result': result, 'mistakes': mistakes, 'image':image, 'button':False})

class Enter_Result(View):

    def get(self, request):
        form=MyResultForm
        return render(request, 'form.html', {'form':form})

    def post(self, request):
        form=MyResultForm(request.POST)
        data=Game.objects.order_by('id')[0]

        if form.is_valid():
            total_save=data.total_for_save
            total_mistakes_save=data.mistakes
            result=form.save(commit=False)
            result.total_tasks = total_save
            result.mistakes = total_mistakes_save
            result.number_of_sessions=data.session
            result.examples_of_mistakes = data.mistakes_examples
            result.save()
            data.save()
            Game.objects.filter(permission=False).delete()

            return redirect('start')

        return redirect('mathtrainer:enter_result')

Trainer/templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Тренажер таблицы умножения</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>


{%block trainer%} {%endblock%}

<body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Trainer/templates/finish.html
{% extends 'base.html'%}
{% block trainer %}
</head>
<body>
<h1>Упражнение закончено. <br>  <br> Всего примеров: {{result}}</h1>
<br>
<h1>Не правильных: {{mistakes}}</h1>
{% if button %}
<a href={% url 'mathtrainer:enter_result' %} class="btn btn-info mb-2">Ввести результаты</a>
{% else %}
<a href={% url 'mathtrainer:trainer_app' %} class="btn btn-info mb-2">Работа над ошибками</a>
{% endif %}
<p>
<img src="{{image}}" width="300" height="300">
</p>
</body>
</html>
{% endblock %}

Trainer/templates/form.html
{% extends 'base.html'%}
{% block trainer %}
<body>
<form method="post", action={% url 'mathtrainer:enter_result' %}>
  {{form.as_p}}
    {% csrf_token %}
  <input type="submit" value="Отправить">
</form>
</body>
</html>
{% endblock %}

Trainer/templates/index.html
{% extends 'base.html'%}
{% block trainer %}
<a href={% url "mathtrainer:math_start" %}><button>Таблица умножения</button></a>
<button>Английский язык Артем</button>
<button>Английский язык Максим</button>
{% endblock %}

Trainer/templates/mathtrainer.html
{% extends 'base.html'%}
{% block trainer %}

<h1>Сколько примеров?</h1>

<form method="post" action=''>
    {% csrf_token %}
    <input autofocus name="number" height="30" type="number">
    <input type="submit" value="Отправить">
      <p>Выберите что-то одно:</p>

  <div>
    <input type="radio" id="contactChoice1"
     name="difficult" value="multi" checked="checked">
    <label for="contactChoice1">Только умножение</label>
      <br>
    <input type="radio" id="contactChoice2"
     name="difficult" value="complex">
    <label for="contactChoice2">Умножение и деление</label>
    <br>
    <input type="radio" id="contactChoice3"
     name="difficult" value="divide">
    <label for="contactChoice3">Только деление</label>
</form>
</body>

{% endblock %}



</html>

Trainer/templates/trainer_app.html
{% extends 'base.html'%}
{% block trainer %}
<body>
<h1>Пример № {{number_task}}</h1>
<h1>{{a}} = </h1>
    <form method="post" action=''>
         {% csrf_token %}
        <input autofocus name="answer" type="number">
        <input type="submit" value="Ответить">
    </form>
{% if messages %}
        {% for message in messages %}
        <p class="alert alert-info" role="alert">{{message}}</p>
        {% endfor %}
        {% endif %}
{{counter}}
{% for t in tasks_deb%}
<p>{{t}}</p>
{% endfor %}
</body>


</html>
{% endblock %}